# Generated by Django 5.2.8 on 2025-11-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratinguser',
            options={'ordering': ['user'], 'verbose_name': 'Профиль оценок пользователя', 'verbose_name_plural': 'Профили оценок пользователя'},
        ),
    ]
