# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_ratinguser_profile_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='average_rating',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Средняя оценка'),
        ),
    ]
