# Generated by Django 5.2.8 on 2025-12-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
