# Generated by Django 5.2.8 on 2025-12-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_profile_country_remove_profile_user'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
